#!/bin/sh
PRG="$0"
while [ -h "$PRG" ]; do
	ls=`ls -ld "$PRG"`
	link=`expr "$ls" : '.*-> \(.*\)$'`
	if expr "$link" : '/.*' > /dev/null; then
		PRG="$link"
	else
		PRG=`dirname "$PRG"`/"$link"
	fi
done
PRGDIR=`dirname "$PRG"`
cd $PRGDIR

git add .
git commit -a -m "update `date +%F\ %T`"
git push origin master
